openapi: '3.0.2'
info:
  title: Form API
  description: API specification for form service
  version: '0.0.0'

paths:
  /forms:
    $ref: '../gateway.yml#/paths/~1forms'
  /forms/{formID}:
    $ref: '../gateway.yml#/paths/~1forms~1{formID}'
  /responses:
    $ref: '../gateway.yml#/paths/~1responses'
  /responses/{responseID}:
    $ref: '../gateway.yml#/paths/~1responses~1{responseID}'
  /responses/{responseID}/tags:
    $ref: '../gateway.yml#/paths/~1responses~1{responseID}~1tags'
  /tags:
      $ref: '../gateway.yml#/paths/~1tags'


    
components:
  schemas:
    form:
      properties:
        id:
          type: integer
        name:
          type: string
        createdAt:
          type: string
          format: date-time
        userID:
          type: integer

    newFormRequest:
      properties:
         name:
          type: string

    patchResponse:
      properties:
        active:
          type: boolean

    formResponse:
      properties:
        id:
          type: integer
        name:
          type: string
          format: string
        emailAddress:
          type: string
          format: email
        subject:
          type: string
        body:
          type: string
        active:
          type: boolean
        formID:
          type: integer
        tags:
          type: array
          items:
            $ref: "#/components/schemas/tag"

    formResponseURLEncodedForm:
      properties:
        name:
          type: string
          format: string
        email:
          type: string
          format: email
        subject:
          type: string
        body:
          type: string     

    tagRequest:
      properties:
        value:
          type: string

    tag:
      properties:
        value:
          type: string

