# DEPRACATED
openapi: 3.0.0
info:
  title: Emails API
  description: Retreive emails with tags and email templates
  version: 0.1.0

servers:
  -url: https://_.com/v1

paths:
  /emails/{userId}:
    get
      summary: Returns a list of email objects.
      parameters:
        - name: userId
          in: path
          required: true
          description: User ID.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: List of email objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id: 
                      type: integer
                      format: int64
                    subject:
                      type: string
                    body:
                      type: string
                    sender:
                      type: string
                    tags:
                      type: array
    /emails/templates/{userId}:
      get
        summary: Returns a list of email template objects.
        parameters:
          - name: userId
            in: path
            required: true
            description: User ID.
            schema:
              type: integer
              format: int64
              minimum: 1
        responses:
          '200':
            description: List of email template objects.
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      id: 
                        type: integer
                        format: int64
                      subject:
                        type: string
                      body:
                        type: string
