services:
  gateway:
    build: 
      context: ./gateway
      args:
        - PORT=80 
    ports:
      - "80:80"
    environment:
      - ADDR=:80
      - AGG_ADDR=http://logaggregator:8888
      - ACCOUNT_SVC=http://account:8080
      - FORM_SVC=http://form:7070
      - MAILTO_SVC=http://mailto:6060
    depends_on:
      - account
      - form
    restart: 
      "on-failure"
  account:
    build: 
      context: ./account
      args:
        - PORT=8080
    environment:
      - ADDR=:8080
      - AGG_ADDR=http://logaggregator:8888
      - DB_IMPL=sqlite
      - DB_DSN=/database/database.db
      - SESS_IMPL=redis
      - REDIS_ADDR=redis:6379
    volumes:
      - ./test_databases:/database
    depends_on:
      - redis
    restart: 
      "on-failure"
  redis:
    image: "redis:alpine"
    restart: 
      "on-failure"
  form:
    build: 
      context: ./form
      args:
        - PORT=7070
    environment:
      - ADDR=:7070
      - AGG_ADDR=http://logaggregator:8888
      - DB_IMPL=sqlite
      - DB_DSN=/database/database.db
    volumes:
      - ./test_databases:/database
    restart: 
      "on-failure"
  logaggregator:
    build: 
      context: ./logAggregator
      args:
        - PORT=8888
    environment:
      - ADDR=:8888
      - DB_DSN=/database/logs.db
    volumes:
      - ./test_databases:/database
    restart: 
      "on-failure"
  mailto:
    build:
      context: ./mailto
      args:
        - PORT=6060
    environment:
      - ADDR=:6060
      - AGG_ADDR=http://logaggregator:8888
    restart: 
      "on-failure"

    
