services:
  gateway:
    build: 
      context: ./gateway
      args:
        - PORT=80 
    ports:
      - "80:80"
    environment:
      - ADDR=:80
      - AGG_ADDR=http://logaggregator:8888
      - ACCOUNT_SVC=http://account:8080
      - FORM_SVC=http://form:7070
  account:
    build: 
      context: ./account
      args:
        - PORT=8080
    environment:
      - ADDR=:8080
      - AGG_ADDR=http://logaggregator:8888
      - DB_IMPL=sqlite
      - DB_DSN=/database/database.db
    volumes:
      - ./test_databases:/database
  form:
    build: 
      context: ./form
      args:
        - PORT=7070
    environment:
      - ADDR=:7070
      - AGG_ADDR=http://logaggregator:8888
      - DB_IMPL=sqlite
      - DB_DSN=/database/database.db
    volumes:
      - ./test_databases:/database
  logaggregator:
    build: 
      context: ./logAggregator
      args:
        - PORT=8888
    environment:
      - ADDR=:8888
      - DB_DSN=/database/logs.db
    volumes:
      - ./test_databases:/database

    
