services:
  gateway:
    build: ./gateway
    ports:
      - "80:80"
    environment:
      - ADDR=:80
      - AGG_ADDR=http://logaggregator:8888
  account:
    build: ./account
    ports:
      - "8080:8080"
    environment:
      - ADDR=:8080
      - AGG_ADDR=http://logaggregator:8888
      - DB_IMPL=sqlite
      - DB_DSN=/database/accounts.db
    volumes:
      - ./account/database:/database
  logaggregator:
    build: ./logAggregator
    ports:
      - "8888:8888"
    environment:
      - ADDR=:8888
      - DB_DSN=/database/logs.db
    volumes:
      - ./logAggregator/database:/database
    
