name: build backend

on:
  workflow_dispatch:
    
  push:
    branches:
      - "main"
    paths:
      - "services/**"

jobs:
  build:
    name: "Build Backend Containers"  
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      GO111MODULE: on
    steps:
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: '1.15.10'
  
    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: features/deploy
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: docker login
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USER }} 
        password: ${{ secrets.DOCKER_TOKEN }} 
    - name: build and push containers
      run: |
        cd services
        ls -l

        echo "==== Vendor: Gateway ===="
        cd ./gateway && go mod vendor
        cd ..
        
        echo "==== Vendor: Account ===="
        cd ./account && go mod vendor
        cd ..
        
        echo "==== Vendor: Form ===="
        cd ./form && go mod vendor
        cd ..
        
        echo "==== Vendor: LogAggregator ===="
        cd ./logAggregator && go mod vendor
        cd ..
        
        echo "==== Vendor: mailto ===="
        cd ./mailto && go mod vendor
        cd ..
        
        docker-compose -f docker-compose.prod.yml build
        docker-compose -f docker-compose.prod.yml push


      
