name: build backend

on:
  workflow_dispatch:
    
  push:
    branches:
      - "main"
    paths:
      - "services/**"

jobs:
  build:
    name: "Build Backend Containers"  
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: features/deploy
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: docker login
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USER }} 
        password: ${{ secrets.DOCKER_TOKEN }} 
    - name: build and push containers
      run: |
        cd services
        docker-compose -f docker-compose.prod.yml build
        docker-compose -f docker-compose.prod.yml push


      
