on:
  workflow_dispatch:
    
jobs:
  deploy:
   name: Deploy to docker swarm
   runs-on: ubuntu-latest
   env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DB_DSN: ${{ secrets.DB_DSN }} 
   steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
          ref: features/deploy
          token: ${{ secrets.PAT_TOKEN }}
    - name: Deploy to swarm
      uses: sagebind/docker-swarm-deploy-action@v2
      with:
        remote_host: ${{ secrets.SSH_HOST }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        #ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        args: stack deploy --compose-file ./services/docker-compose.prod.yml civicqa
        

