on:
  workflow_dispatch:
    
jobs:
  deploy:
   name: Deploy to docker swarm
   runs-on: ubuntu-latest
   env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DB_DSN: ${{ secrets.DB_DSN }} 
   steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
          ref: features/deploy
          token: ${{ secrets.PAT_TOKEN }}
    - uses: actions/checkout@master
    - name: SCP docker-compose file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./services/docker-compose.prod.yml"
        target: "/root"
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          export DB_DSN="${{ secrets.DB_DSN }}"
          export DOCKER_USER="${{ secrets.DOCKER_USER }}"
          docker stack deploy --compose-file docker-compose.prod.yml civicqa

